github.base.url=https://github.com/
github.api.url=https://api.github.com/
github.api.token=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
github.api.version=2022-11-28
github.username=edzioo@gmail.com
github.password==z9;[jR6]36$t8y
browser=CHROME
headless=false
aut=GITHUB
defaultWait=30
