base.url=https://github.com/
api.url=https://api.github.com/
api.acceptHeader=application/vnd.github+json
api.token=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
api.version=2022-11-28
keep=firstRepo;secondRepo
username=edzioo
email=edzioo@gmail.com
password==z9;[jR6]36$t8y
